apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deployment
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
        - name: sales
          image: sales:0.0.1
          resources:
            requests:
              memory: "100Mi"
              cpu: "500m" # 50ms from 100ms given by scheduler, single threaded Go application
            limits:
              memory: "100Mi"
              cpu: "500m"

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu

          ports:
            - containerPort: 8000
              name: sales-port

---
apiVersion: v1
kind: Service
metadata:
  name: sales-svc
  namespace: sales-system
spec:
  selector:
    app: sales
  ports:
    - port: 8000
      targetPort: 8000
      name: sales-port
